//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zerohungy.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZerohungryEntities : DbContext
    {
        public ZerohungryEntities()
            : base("name=ZerohungryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Food_Collect> Food_Collect { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Moderator> Moderators { get; set; }
        public virtual DbSet<Resturant> Resturants { get; set; }
    }
}
